### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by xp12047** [Warbacon/zunder-zsh#2]
Forgive me, the only person I can contact that I think can help me is you.  
I left a message for you with a new trouble before, but the problem at that time was that the node I installed could not be found.  But I solved this problem perfectly by uninstalling termux.  But here comes a more painful problem.  .  .  
When I use termux to download something and open it with a mobile app other than termux, it crashes.  It was open before.  Help me, please!  
it is very important to me  
![Screenshot_20220514_142410_com rhmsoft edit_edit_7785923913394](https://user-images.githubusercontent.com/56335408/168415337-5d7b186a-103d-4fe0-aad0-3240dc241048.jpg)
![Screenshot_20220514_151106_com termux](https://user-images.githubusercontent.com/56335408/168415340-aa2efa35-e1f4-4a4d-9b3e-0f5eaaf2c38d.jpg)

**Comment by xp12047** [comment]
Google translate is often not easy to use at critical moments

**Comment by Warbacon** [comment]
This doesn't seem a issue from my script... Anyway,  I think you should uncomment the line that says allow-external-apps by removing the first symbol in it (#).

Do not ask for help in the issues tab again please, unless it's a zunder related bug. I will close the issue.

**Comment by xp12047** [comment]
> 这似乎不是我的脚本的问题...无论如何，我认为您应该通过删除其中的第一个符号 (#) 来取消注释允许外部应用程序的行。
> 
> 请不要再次在问题选项卡中寻求帮助，除非它是与 zunder 相关的错误。我会关闭这个问题。
Thank you very much, the problem is solved.  I'm really sorry, I didn't move anything, the termux I just downloaded was confused, thank you for helping me.

**Comment by xp12047** [comment]
This reply is thank you for developing a very useful zsh tool, I like it very much.  When I installed the new termux, it gave me great convenience.  I corrected one of the above replies, I downloaded the latest version of termux and the settings did not change, thanks to your pointing me, otherwise I really don't know how long it will take to solve it.  I'm also trying to learn the basics of this.

**Comment by Warbacon** [comment]
I appreciate your thanks, but this is not the place to ask for answers that are not related to Zunder. At last, if you plan to learn the basics of using a shell, you sould take a look at GNU/Linux. There are many distributions, but you may like Deepin since it is from Asia. You can also try Linux mint or Endeavor os. I personally use Arch Linux, but it's quite an advanced distribution, if you dare, good luck.

Android support may be worse than the one I provide to the Linux distributions I mention in the README, as I don't usually use the shell on Android, it's only there because it's not too hard to port

**Comment by xp12047** [comment]
> 感谢您的感谢，但这里不是要求与 Zunder 无关的答案的地方。最后，如果你打算学习使用 shell 的基础知识，你应该看看 GNU/Linux。有很多发行版，但你可能会喜欢 Deepin，因为它来自亚洲。你也可以试试 Linux mint 或 Endeavor os。我个人使用 Arch Linux，但它是一个相当高级的发行版，如果你敢，祝你好运。
> 
> Android 支持可能比我在 README 中提到的 Linux 发行版提供的支持更差，因为我通常不在 Android 上使用 shell，它只是因为移植起来不太难

Thanks, thanks for the pointers, I think I'll keep that in mind.
