### ISSUE TITLE
I seem to have a problem with my termux after your update

### ISSUE THREAD

**Issue by xp12047** [Warbacon/zunder-zsh#3]
![Screenshot_20220609_172643_com termux](https://user-images.githubusercontent.com/56335408/172814939-cb722536-5f91-429e-a527-45990a398df4.jpg)
I see these error messages after opening it.  pkg doesn't work either, rm doesn't work either

**Comment by Warbacon** [comment]
Did you update yesterday? I enabled again exa because it seems to be working now if you update your termux installation (pkg update). Anyway, this is a warning from Powerlevel10k, which says that something is printing an output before the pormpt initializes. I need to see the last line of this warning to know what's going on.

**Comment by xp12047** [comment]
it updates itself      
As soon as I open it, it starts giving errors   
![Screenshot_20220609_192547_com termux](https://user-images.githubusercontent.com/56335408/172836343-b36a7b15-ccb3-4ad7-b6d2-05a04813df17.jpg)
![Screenshot_20220609_192535_com termux](https://user-images.githubusercontent.com/56335408/172836351-3eea6694-e4c2-4641-bec2-62cd3b791119.jpg)

I still remember that I changed the env file in the cargo folder to have it modify its bin directory, and then this happened when I opened termux.  I did not actively update

**Comment by xp12047** [comment]
Sorry, I don't seem to describe it correctly. It should be said that I got an error when I opened it.  It doesn't seem to be updated

**Comment by xp12047** [comment]
![Uploading Screenshot_20220609_193605_com.termux.jpg…]()

**Comment by xp12047** [comment]
![Uploading Screenshot_20220609_193700_com.termux.jpg…]()

**Comment by xp12047** [comment]
![Screenshot_20220609_193700_com termux](https://user-images.githubusercontent.com/56335408/172838447-00f778d1-36ab-4772-90b3-c7051f0feda4.jpg)

**Comment by Warbacon** [comment]
I don't think that this problem is related to Zunder. Since I don't know what you actually did, I can only recommend deleting all data from your termux installation. The problem seems to be that the system does not detect the /bin directory, where all the installed programs are. Since rm, cd and other commands are in this folder, you can't do anything right now except reset everything.

**Comment by xp12047** [comment]
You have helped me again.  It really has nothing to do with Zunder.  I entered failsafe in termux, deleted the env file in cargo, and all errors are gone.  Thank you, I see you updated and I also think, how do I update it?

**Comment by Warbacon** [comment]
To upgrade to the latest version, simply run the latest version of the script. Clone the repo again and run the script using ./run.sh.

**Comment by xp12047** [comment]
thanks

> 要升级到最新版本，只需运行最新版本的脚本。再次克隆 repo 并使用 ./run.sh 运行脚本。

thanks
